pub mod command;
pub mod state;
pub mod view;
pub mod widget;

use crate::trade::{Instrument, Order};
use druid::im::{vector, Vector};
use druid::piet::{PietTextLayoutBuilder, TextStorage as PietTextStorage};
use druid::text::{Attribute, RichText, TextStorage};
use druid::{
    Color, Data, Env, FontFamily, FontStyle, FontWeight, Lens, Point, Rect, Size, WindowId,
};
use qbox_core::broker::Bar;
use std::path::Path;
use std::sync::Arc;
use view::indicator::MyRadio;
use view::MainView;

pub const VERSION: &str = "1.0";

pub const NAME: &str = "QBox量化";
pub const NAME2: &str = "Qbox量化";
pub const APP_NAME: &str = "技术指标";
pub const DATA_DIR: &str = "data";

pub fn chart_app() {}

pub fn trade_app() {}

pub fn get_primary_work_rect() -> Option<Rect> {
    for m in druid::Screen::get_monitors().iter() {
        if m.is_primary() {
            return Some(m.virtual_work_rect());
        }
    }

    None
}

#[derive(Data, Lens, Clone)]
pub struct State {
    pub period: i32,
    pub data: Arc<Vec<Bar>>,
    pub symbol: Arc<Vec<String>>,
    pub radio: MyRadio,
    pub windid: Option<Arc<WindowId>>,
    pub coord: Option<Point>,
    pub name: NameText,
    pub name2: NameText,
    pub memo_size: Option<Size>,
    pub left_menu: bool,
    pub current_view: MainView,
    pub scale: f64,
    pub data_path: String, //数据目录
    pub instruments: Arc<Vec<Instrument>>,
    pub current_instrument: Instrument,
    pub self_instruments: Arc<Vec<Instrument>>,
    pub orders: Arc<Vec<Order>>,
}

impl Default for State {
    fn default() -> Self {
        let path = format!(
            "{}",
            std::env::current_exe().unwrap().parent().unwrap().display()
        );
        Self::new(&path)
    }
}

impl State {
    pub fn new<P: AsRef<Path>>(path: P) -> Self {
        let text = RichText::new(NAME.into())
            .with_attribute(0..4, Attribute::text_color(Color::rgb(1.0, 0.2, 0.1)))
            .with_attribute(0..4, Attribute::size(24.0))
            .with_attribute(0..4, Attribute::font_family(FontFamily::SERIF))
            .with_attribute(4.., Attribute::text_color(Color::rgb(1.0, 1.0, 1.0)))
            .with_attribute(4.., Attribute::size(12.0))
            .with_attribute(4.., Attribute::weight(FontWeight::BOLD))
            .with_attribute(4.., Attribute::style(FontStyle::Italic));

        let text2 = RichText::new(NAME2.into())
            .with_attribute(0..4, Attribute::text_color(Color::rgb(1.0, 0.2, 0.1)))
            .with_attribute(0..4, Attribute::size(16.0))
            .with_attribute(0..4, Attribute::font_family(FontFamily::SERIF))
            .with_attribute(4.., Attribute::text_color(Color::rgb(1.0, 1.0, 1.0)))
            .with_attribute(4.., Attribute::size(8.0))
            .with_attribute(4.., Attribute::weight(FontWeight::BOLD))
            .with_attribute(4.., Attribute::style(FontStyle::Italic));
        let path = path.as_ref().join(DATA_DIR);
        std::fs::create_dir_all(path.as_path()).unwrap();
        State {
            name: NameText::new(text),
            name2: NameText::new(text2),
            period: Default::default(),
            data: Default::default(),
            symbol: Default::default(),
            radio: Default::default(),
            windid: None,
            coord: None,
            memo_size: None,
            left_menu: true,
            current_view: Default::default(),
            scale: 1.0,
            data_path: path.to_str().unwrap().to_string(),
            current_instrument: Default::default(),
            self_instruments: Arc::new(vec![]),
            orders: Arc::new(vec![]),
            instruments: Arc::new(vec![
                Instrument::default(),
                Instrument {
                    symbol: "白银2021".to_owned(),
                    security_id: "BY2021".to_owned(),
                    ..Default::default()
                },
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
                Instrument::default(),
            ]),
        }
    }
}

impl State {
    pub fn flush_symbol(&mut self, symbol: &str) {
        if let Ok(file) = std::fs::File::open(format!("{}.csv", symbol)) {
            let mut rdr = csv::Reader::from_reader(file);
            let data = Arc::make_mut(&mut self.data);
            data.clear();
            for result in rdr.deserialize() {
                if let Ok(bar) = result {
                    data.push(bar);
                }
            }
        }
    }
}

#[derive(Data, Lens, Clone)]
pub struct NameText {
    text: RichText,
}

impl NameText {
    pub fn new(text: RichText) -> Self {
        Self { text }
    }
}

impl PietTextStorage for NameText {
    fn as_str(&self) -> &str {
        self.text.as_str()
    }
}
impl TextStorage for NameText {
    fn add_attributes(&self, builder: PietTextLayoutBuilder, env: &Env) -> PietTextLayoutBuilder {
        self.text.add_attributes(builder, env)
    }
}
